GET
  FILE='C:\pasw18\Samples\English\1991 U.S. General Social Survey.sav'.
DATASET name DataSet1.
* Custom Tables.
RECODE educ  (0 thru 11=1) (12 thru 15=2) (16 thru Highest=3).
 CTABLES
  /TABLE educ[c] [COUNT F40.0, ROWPCT.COUNT PCT40.1] BY  race
  /SLABELS POSITION=ROW
  /COMPARETEST TYPE=PROP ALPHA=0.05 ADJUST=BONFERRONI ORIGIN=COLUMN INCLUDEMRSETS=YES 
    CATEGORIES=ALLVISIBLE MERGE=NO.

SPSSINC MODIFY TABLES subtype="Custom Table"
SELECT="Count" DIMENSION= ROWS
LEVEL = -1  PROCESS = PRECEDING 
/STYLES  APPLYTO=DATACELLS 
CUSTOMFUNCTION="customstylefunctions.boldIfEndsWithAtoZLetter".


 SPSSINC MERGE TABLES MATCHLABEL="Count" ATTACH=ROWS
MODE=MERGE 
/OPTIONS HIDE=NO APPENDTITLE=NO APPENDCAPTION=NO ADDLABELLEAF=NO
HALIGN=RIGHT SEPARATOR="  - ".

* no labels.
CTABLES
  /TABLE educ[c] [COUNT F40.0, ROWPCT.COUNT PCT40.1] BY  race
  /SLABELS POSITION=COLUMN visible=yes
  /COMPARETEST TYPE=PROP ALPHA=0.05 ADJUST=BONFERRONI ORIGIN=COLUMN INCLUDEMRSETS=YES 
    CATEGORIES=ALLVISIBLE MERGE=NO.


SPSSINC MERGE TABLES  ATTACH=columns
MODE=MERGE 
/OPTIONS HIDE=NO APPENDTITLE=NO APPENDCAPTION=NO ADDLABELLEAF=NO
HALIGN=RIGHT SEPARATOR="  - ".


CTABLES
  /TABLE educ[c] [COUNT F40.0, ROWPCT.COUNT PCT40.1] BY  race
  /SLABELS POSITION=row visible=no
  /COMPARETEST TYPE=PROP ALPHA=0.05 ADJUST=BONFERRONI ORIGIN=COLUMN INCLUDEMRSETS=YES 
    CATEGORIES=ALLVISIBLE.

SPSSINC CENSOR TABLES
CRITLABEL="Count" TESTTYPE="<" CRITVALUE=20
DIRECTION=COLUMN NEIGHBORS=1
SUBTYPE="Custom Table"
/OPTIONS 
SYMBOL=" ***".


SPSSINC MERGE TABLES  ATTACH=rows MATCHLABEL="Count"
MODE=MERGE
/OPTIONS HIDE=NO APPENDTITLE=NO APPENDCAPTION=NO
HALIGN=RIGHT SEPARATOR="  - ".


SPSSINC MODIFY TABLES subtype="'Custom Table'"
SELECT=0 
DIMENSION= rows
LEVEL = -1  PROCESS = PRECEDING 
PRINTLABELS=TRUE
/STYLES  APPLYTO=DATACELLS.



DATASET ACTIVATE DataSet1.

