
* Merge two correlations tables.
GET FILE= "c:/spss22/samples/english/employee data.sav".
DATASET NAME emp.

set olang=english.
CORRELATIONS
  /VARIABLES=salary salbegin jobtime prevexp
  /PRINT=TWOTAIL SIG
  /MISSING=PAIRWISE.
NONPAR CORR
  /VARIABLES=salary salbegin jobtime prevexp
  /PRINT=KENDALL TWOTAIL SIG
  /MISSING=PAIRWISE.

SPSSINC MERGE TABLES ATTACH=COLUMNS
MODE=MERGE PRIROWLEVELS=1 3 PRICOLLEVELS=1 STANDARDFUNCTIONS=NO SECROWLEVELS=3 5 SECCOLLEVELS=1 
TABLES="'Correlations'" "'Correlations'"
/OPTIONS HIDE=YES APPENDTITLE=YES APPENDCAPTION=YES
HALIGN=RIGHT SEPARATOR="\n" PRINTLEVELS=NO.

set olang=german.
* error - no such table.
SPSSINC MERGE TABLES ATTACH=COLUMNS
MODE=MERGE PRIROWLEVELS=1 3 PRICOLLEVELS=1 STANDARDFUNCTIONS=NO SECROWLEVELS=3 5 SECCOLLEVELS=1 
TABLES="'Correlations'" "'Correlationsxyz'"
/OPTIONS HIDE=YES APPENDTITLE=YES APPENDCAPTION=YES
HALIGN=RIGHT SEPARATOR="\n" PRINTLEVELS=NO.
