GET
  FILE='C:\spss22\samples\english\employee data.sav'.
DATASET NAME DataSet1 WINDOW=FRONT.
DATASET ACTIVATE DataSet1.
* Custom Tables.
CTABLES
  /TABLE jobcat > gender > salary [MEAN, COUNT F40.0] BY educ
  /COMPARETEST TYPE=MEAN ALPHA=0.05 ADJUST=BONFERRONI ORIGIN=COLUMN INCLUDEMRSETS=YES 
    CATEGORIES=ALLVISIBLE MEANSVARIANCE=ALLCATS.

SPSSINC MERGE TABLES MATCHLABEL="Mean" ATTACH=COLUMNS
MODE=MERGE 
/OPTIONS HIDE=YES APPENDTITLE=YES APPENDCAPTION=YES
HALIGN=RIGHT SEPARATOR="\n".

* test with table types.
CTABLES
  /TABLE jobcat > gender >salbegin [MEAN, COUNT F40.0] BY educ
  /COMPARETEST TYPE=MEAN ALPHA=0.05 ADJUST=BONFERRONI ORIGIN=COLUMN INCLUDEMRSETS=YES 
    CATEGORIES=ALLVISIBLE MEANSVARIANCE=ALLCATS.
DATASET ACTIVATE DataSet1.
SPSSINC MERGE TABLES MATCHLABEL="Count" ATTACH=COLUMNS
MODE=MERGE 
TABLES="'Custom Table'" "'Comparisons of Means'"
/OPTIONS HIDE=YES APPENDTITLE=YES APPENDCAPTION=YES
HALIGN=RIGHT SEPARATOR="\n".


