FILE HANDLE data /NAME ="c:/spss17/samples/english".
get file="data/cars.sav".


begin program.
import spss, tables17
cmd="CTABLES /TABLE origin BY accel [MEAN, COUNT]  /SLABELS POSITION=ROW."

rc= tables17.censorLatest(cmd=cmd, critvalue=80, 
symbol='', neighborlist=[-1], direction='col')
print "return code:", rc
end program.

CTABLES /TABLE origin BY accel [MEAN, COUNT]  /SLABELS POSITION=ROW.

SPSSINC CENSOR TABLES COMMAND="CTABLES /TABLE origin BY accel [MEAN, COUNT]  /SLABELS POSITION=ROW."
CRITLABEL="Count" CRITVALUE=80 NEIGHBORS=-1 DIRECTION=COLUMN, TESTTYPE="<"
/OPTIONS SYMBOL="*".

SPSSINC CENSOR TABLES COMMAND="CTABLES /TABLE origin BY accel [MEAN, COUNT]."
CRITLABEL="Count" CRITVALUE=80 NEIGHBORS=-1 DIRECTION=ROW, TESTTYPE=">"
/OPTIONS SYMBOL="*".

SPSSINC CENSOR TABLES COMMAND="CTABLES /TABLE origin BY accel [MEAN, COUNT]."
CRITLABEL="Count" CRITVALUE=80 NEIGHBORS=-1 DIRECTION=ROW, TESTTYPE=">"
/OPTIONS SYMBOL="*" caption="different text".

CTABLES /TABLE YEAR>MPG[COUNT MEAN SUM] BY ORIGIN.
SPSSINC CENSOR TABLES SUBTYPE='Custom Table' CRITVALUE=9 NEIGHBORS=1 2.

CTABLES /TABLE YEAR>MPG[COUNT MEAN SUM] BY ORIGIN.
SPSSINC CENSOR TABLES SUBTYPE='Custom Table' CRITVALUE=9 NEIGHBORS=1 2
/OPTIONS HIDECRITFIELD APPENDCAPTION=NO SYMBOL="secret".

SPSSINC CENSOR TABLES /HELP.



CTABLES /TABLE origin BY accel [MEAN, COUNT]  /SLABELS POSITION=ROW.
CTABLES  /TABLE year [C][COUNT] BY origin [C] /SLABELS POSITION=ROW /COMPARETEST TYPE=PROP.


CTABLES  /TABLE year > mpg [MEAN count] BY origin.

